language: php
php:
  - '7.1'
  - nightly
services:
  - mysql
before_install:
  - mysql -e 'create database homestead_test;'
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed
