version: 2
jobs:
  precacheNode:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  precacheComposer:
    docker:
      - image: bitnami/laravel
    steps:
      - checkout
      - restore_cache:
          key: composer-cache-{{ checksum "composer.json" }}
      - run: |
          composer install
          touch database/database.sqlite
          cp .env.circle .env
          php artisan migrate
          php artisan db:seed
      - save_cache:
          key: composer-cache-{{ checksum "composer.json" }}
          paths:
            - vendor
            - database
  test:
    docker:
      - image: phpunit/phpunit:5.7.12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: composer-cache-{{ checksum "composer.json" }}
      - run: |
          mv /home/circleci/project/node_modules .
          mv /home/bitnami/project/vendor .
          mv /home/bitnami/project/database/database.sqlite database/.
          cp .env.circle .env
          phpunit
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.09.0-ce
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: |
          sudo mkdir /home/bitnami
          sudo chmod 777 /home/bitnami
      - restore_cache:
          key: composer-cache-{{ checksum "composer.json" }}
      - run: |
          sudo mv /home/bitnami/project/vendor .
          mv /home/circleci/project/node_modules .
          docker build -t d.wplr.rocks/2by2:latest -t d.wplr.rocks/2by2:$CIRCLE_BUILD_NUM -t d.wplr.rocks/2by2:$CIRCLE_SHA1 .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD -e $DOCKERHUB_EMAIL d.wplr.rocks
          docker push d.wplr.rocks/2by2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - precacheComposer
      - precacheNode
      - test:
          requires:
            - precacheComposer
            - precacheNode
      - build:
          requires:
            - precacheComposer
            - precacheNode
            - test
          filters:
            branches:
              only: master